[package]
name = "raytracer-5607"
version = "0.1.0"
authors = ["Bridger Herman <herma582@umn.edu>"]

[dependencies]
image = "0.19"
clap = "2.32"
conrod = { version = "0.61", features = ["glium", "winit"] }

[dev-dependencies]
glm = "0.2"
